/* eslint-disable @typescript-eslint/no-unsafe-member-access */
import { Text, Title } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import { api } from "~/utils/api";

const ListingPage: NextPage = () => {
  const router = useRouter();
  const listing = api.listings.get.useQuery(
    { listingId: router.query.id as string },
    { enabled: !!router.query.id }
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title>{listing.data?.name}</Title>
      <Text>{listing.data?.description}</Text>
      <Text>$ {listing.data?.price}</Text>
    </>
  );
};

export default ListingPage;
