/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */

import { Box } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";

import { ItemCard } from "~/components/ItemCard";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const listings = api.listings.list.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        {listings.data?.map((listing) => (
          <ItemCard
            key={listing.id}
            id={listing.id}
            name={listing.name}
            description={listing.description}
            price={listing.price}
          />
        ))}
      </Box>
    </>
  );
};

export default Home;
