import { useUser } from "@clerk/nextjs";
import { Text } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const { user, isSignedIn } = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isSignedIn ? (
        <Text size={"xl"}>Hello,{user?.fullName}</Text>
      ) : (
        <Text>You&apos;re Not Signed in</Text>
      )}
    </>
  );
};

export default Home;
